import { NextRequest, NextResponse } from "next/server";
import { generateMcqsFromMaterial, detectMaterialKind } from "@/lib/materials/mcq";

export const dynamic = "force-dynamic";
export const maxDuration = 60;

const MAX_BYTES = 20 * 1024 * 1024; // 20 MB

/**
 * POST /api/materials/mcq  (multipart/form-data)
 *   file:      the learning material (PDF, PPTX, DOCX, TXT/MD)
 *   maxQuestions: optional cap (default 10, max 10)
 *
 * Returns grounded MCQs: every question carries chunkIndex + a verbatim
 * quote from the document, and `mode` states whether an LLM or the
 * deterministic fallback generated it. No silent AI dependence.
 */
export async function POST(request: NextRequest) {
  let form: FormData;
  try {
    form = await request.formData();
  } catch {
    return NextResponse.json({ error: "Expected multipart/form-data with a `file` field." }, { status: 400 });
  }
  const file = form.get("file");
  if (!(file instanceof File)) {
    return NextResponse.json({ error: "Missing `file` field." }, { status: 400 });
  }
  const kind = detectMaterialKind(file.name, file.type);
  if (!kind) {
    return NextResponse.json(
      { error: `Unsupported file type "${file.name}". Supported: PDF, PPTX, DOCX, TXT/MD.` },
      { status: 415 },
    );
  }
  if (file.size > MAX_BYTES) {
    return NextResponse.json({ error: "File too large (max 20 MB)." }, { status: 413 });
  }
  const maxQuestionsRaw = form.get("maxQuestions");
  const maxQuestions = typeof maxQuestionsRaw === "string" ? Number(maxQuestionsRaw) || undefined : undefined;

  try {
    const buffer = await file.arrayBuffer();
    const result = await generateMcqsFromMaterial(buffer, file.name, file.type, { maxQuestions });
    return NextResponse.json({
      documentTitle: result.documentTitle,
      kind: result.kind,
      chunkCount: result.chunkCount,
      mode: result.mode,
      groundedChunks: result.groundedChunks,
      questionCount: result.questions.length,
      questions: result.questions,
      note:
        result.mode === "llm"
          ? "Generated by an LLM strictly grounded in the uploaded document; every question cites its source chunk."
          : "Generated deterministically from the document text (no LLM configured) — cloze questions whose answers appear verbatim in the cited chunk.",
    });
  } catch (e) {
    const message = e instanceof Error ? e.message : "MCQ generation failed";
    const status = message.includes("Unsupported") ? 415 : message.includes("extract") ? 422 : 500;
    return NextResponse.json({ error: message }, { status });
  }
}
